default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: <%= Figaro.env.GATE_DB_HOST %>
  port: <%= Figaro.env.GATE_DB_PORT %>
  username: <%= Figaro.env.GATE_DB_USER %>
  password: <%= Figaro.env.GATE_DB_PASSWORD %>


development:
  <<: *default
  database: gate_development
  properties:
    useSSL: false

test:
  <<: *default
  database: gate_test
  properties:
    useSSL: false

integration:
  <<: *default
  database: <%= Figaro.env.GATE_DB_NAME %>

production:
  <<: *default
  database: <%= Figaro.env.GATE_DB_NAME %>
