default: &default
  host: <%= Figaro.env.CACHE_HOST %>
  port: <%= Figaro.env.CACHE_PORT %>
  limit: 20

development:
  <<: *default

test:
  <<: *default

integration:
  <<: *default

production:
  <<: *default
