default: &default
  host: localhost
  port: 6379
  limit: 20

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: <%= ENV['CACHE_HOST'] %>
  port: <%= ENV['CACHE_PORT'] %>
